name: poc

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: ./sql.txt
        destination: s3://shivv/f1
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.gitignore' --exclude '.github/*' --exclude '.github' --exclude 'README.md'
        AWS_S3_BUCKET: shivv
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # 
        
  
